### ISSUE TITLE
Improve Google API error message parsing 

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/google-drive-extractor#13]
[Here](https://github.com/keboola/google-drive-extractor/blob/master/src/Keboola/GoogleDriveExtractor/Extractor/Extractor.php#L67) there could be a method that would route some known error types to a more meaningful UserExceptions.

**Comment by tomasfejfar** [comment]
Ref.: https://keboola.zendesk.com/agent/tickets/9921

**Comment by tomasfejfar** [comment]
Maybe at least make the JSON pretty printed to improve readability.

**Comment by SMKozuch** [comment]
Just to add, the current error message is something like this:

```
[2019-03-01 00:00:24] ex-google-drive.ERROR: Google Drive Error: Client error: `POST
 https://www.googleapis.com/oauth2/v3/token` resulted in a `400 Bad Request` response: { "error": 
"invalid_grant", "error_description": "Bad Request" } {"message":"Client error: `POST 
https://www.googleapis.com/oauth2/v3/token` resulted in a `400 Bad Request` response:\\n{\\n 
\"error\": \"invalid_grant\",\\n \"error_description\": \"Bad Request\"\\n}\\n","reason":"Bad 
Request","sheet":
{"id":2,"fileId":"1y_XXXXXXXXXXX","fileTitle":"XXXX","sheetId":"433959412","sheetTitle":"XXXXX",
"outputTable":"table","header":{"rows":1,"columns":[]},"enabled":true}} []
```

It can be kinda hard for end-users to read and debug themselves. Maybe a  status code of the request, `response.error` and `response.error_description` would suffice?
