### ISSUE TITLE
Google Team Drive support

### ISSUE THREAD

**Issue by padak** [keboola/google-drive-extractor#16]
Existing file picker doesn't support Team Drive. It might be a small switch on our side. We got a few upvotes to this feature in PB.

**Comment by MiroCillik** [comment]
https://stackoverflow.com/questions/46658325/google-apps-script-google-picker-for-team-drive

**Comment by MiroCillik** [comment]
Solved https://monosnap.com/file/bDQzIOvzprLbGVmTODQkXAGh1Mmoer
