### ISSUE TITLE
Undefined index error_description

### ISSUE THREAD

**Issue by odinuv** [keboola/google-drive-extractor#18]
https://github.com/keboola/google-drive-extractor/blob/master/src/Keboola/GoogleDriveExtractor/Extractor/ExceptionHandler.php#L29

https://keboola.slack.com/archives/C09U3R1J4/p1558147201010400

Patrne to vzniklo v https://github.com/keboola/google-drive-extractor/commit/04b73e1b028b0171af2b2b14781c5d041b100f86 zvazil bych revert?

**Comment by tomasfejfar** [comment]
Revertnuto - mrknu na to pak v pondělí.

**Comment by tomasfejfar** [comment]
Revers #15
