### ISSUE TITLE
Extrahujeme jen první sloupec

### ISSUE THREAD

**Issue by padak** [keboola/google-drive-extractor#2]
Vokurka našel situaci, kdy mu exportujeme jen jeden sloupec z tabulky. Popsal to tady: https://keboola.zendesk.com/agent/tickets/5528 Já jsem to zkopíroval a nepovedlo se mi to donutit fungovat ok - tady je moje cfg: https://connection.keboola.com/admin/projects/901/extractors/keboola.ex-google-drive/209236638

Vypadá to na bug.

Padák

**Comment by MiroCillik** [comment]
Uz je opravene nejaku dobu.
